services:
  - type: web
    name: bupulse-backend
    runtime: node
    rootDirectory: backend
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: PUPPETEER_SKIP_CHROMIUM_DOWNLOAD
        value: true
      - key: PUPPETEER_EXECUTABLE_PATH
        value: /usr/bin/google-chrome-stable
    buildpacks:
      - url: https://github.com/render-examples/render-buildpack-google-chrome
